[package]
name = "rcsv"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
colored = "3.0.0"
unicode-width = "0.2.2"

